AllCops:
  Exclude:
    - "Gemfile"
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/{rails,rake}"
    - !ruby/regexp /old_and_unused\.rb$/

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
